name: connectech_pro_flutter
description: A Flutter e-learning application for Connectech Pro
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Backend & Authentication
  supabase_flutter: ^2.3.4
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.4.0
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  
  # Charts & Data Visualization
  fl_chart: ^0.66.0
  
  # Video Player
  video_player: ^2.8.2
  chewie: ^1.7.4
  
  # File Handling
  path_provider: ^2.1.2
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700 